name: monalisa_app_001
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.4

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  ai_barcode_scanner: ^7.0.0
  dio: ^5.7.0
  dotenv: ^4.2.0
  flutter_dotenv: ^6.0.0
  material_symbols_icons: ^4.2892.0
  flutter_riverpod: ^3.0.0
  formz: ^0.8.0
  go_router: ^16.3.0
  google_fonts: ^6.2.1
  http_parser: ^4.1.2
  idempiere_rest: ^1.0.2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  webview_flutter: ^4.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_onscreen_keyboard: ^0.4.0+1
  intl: ^0.20.2
  input_dialog: ^0.1.1
  simple_barcode_scanner: ^0.3.0
  change_app_package_name: ^1.5.0
  awesome_dialog: ^3.2.1
  flutter_addons: ^2.5.0
  fl_chart: ^1.1.1
  pin_code_fields: ^8.0.1
  card_swiper: ^3.0.1
  country_picker: ^2.0.27
  pinput: ^5.0.1
  mobile_scanner: ^7.1.2
  flutter_tabler_icons: ^1.43.0
  slide_to_confirm: ^1.1.0
  get_storage: ^2.1.1
  printing: ^5.14.2
  pdf: ^3.11.3
  flutter_net_printer: ^1.0.4
  esc_pos_utils_plus: ^2.0.4
  image: ^4.5.4
  random_name_generator: ^1.5.0
  flutter_esc_pos_network: ^1.0.3
  qr_flutter: ^4.1.0
  barcode_image: ^2.0.3
  flutter_exit_app: ^2.0.0
  barcode: any
  http: any
  permission_handler: any
  barcode_widget: ^2.0.4
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/certificates/my_certificate.pem
    - assets/certificates/monalisa_com_py.pem
    - assets/images/
    - google_fonts/
    - assets/loaders/
    - google_fonts/montserrat_alternates/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icono-monalisa.png"  # Ruta de tu icono
  adaptive_icon_foreground: "assets/images/icono-monalisa.png"  # Opcional
  adaptive_icon_background: "#ffffff"  # Fondo del icono adaptativo (Android)